### ISSUE TITLE
Parameter for disabling continuous update

### ISSUE THREAD

**Issue by jbednar** [ioam/paramnb#34]
By default, paramnb.Widgets will execute the callback or the next cell every time it receives an event from ipywdgets indicating that a parameter value has changed.  This provides responsive updates, when the callback only takes a few hundred milliseconds to run, but when it's slower, a sequence of such updates can get queued up, slowing everything to a crawl until the display catches up.  See e.g. the "alpha" parameter in https://anaconda.org/jbednar/nyc_taxi-paramnb/notebook .

https://github.com/ipython/ipywidgets/issues/663 has some suggestions for what to do in such cases. Maybe we should add a "continuous_update" parameter to paramnb.Widgets that can be turned off when we know we will have a slow callback, so that the callback will be executed only once someone completes a drag motion?

**Comment by philippjfr** [comment]
This was added in https://github.com/ioam/paramnb/pull/36.
