### ISSUE TITLE
ipywidgets 7 + paramnb = strange scrolling behavior

### ISSUE THREAD

**Issue by ceball** [ioam/paramnb#70]
If you scroll a notebook using the mouse wheel and the cursor is above (or passes over) a widget, the widget scrolls and vanishes.

**Comment by jbednar** [comment]
I assume this issue should be filed on ipywidgets 7, but that would require narrowing it down to a reproducible test case.  My guess is that it happens when you put a widget in a box, as I believe we do here, and there may be some setting to turn off that behavior.

**Comment by ceball** [comment]
Happily I don't get this problem any more; all I get is this:

<img width="1003" alt="screen shot 2017-10-01 at 8 37 55 pm" src="https://user-images.githubusercontent.com/1929/31058253-ab4979c8-a6e8-11e7-8bc7-5849385d6f30.png">

**Comment by ceball** [comment]
Or this (exciting color change in the new version):

<img width="1004" alt="screen shot 2017-10-01 at 8 42 24 pm" src="https://user-images.githubusercontent.com/1929/31058280-12242b70-a6e9-11e7-9c26-5708e12ba53a.png">

**Comment by ceball** [comment]
Unfortunately the problem eventually came back. So far I have narrowed it down to a change in ipywidgets that happened after 6.0.1 and by 7.0.0, and that we get the problem when the docstring is long enough...

# 6.0.1
<img width="1198" alt="screen shot 2017-10-01 at 8 49 26 pm" src="https://user-images.githubusercontent.com/1929/31058392-acc3e534-a6ea-11e7-8e84-8be766174e2b.png">

# 7.0.0

<img width="1171" alt="screen shot 2017-10-01 at 8 50 25 pm" src="https://user-images.githubusercontent.com/1929/31058394-bbb40862-a6ea-11e7-9374-0c6cc151a4b9.png">

<img width="1181" alt="screen shot 2017-10-01 at 8 50 48 pm" src="https://user-images.githubusercontent.com/1929/31058398-c66eefec-a6ea-11e7-9289-0e5a0c72a543.png">

**Comment by ceball** [comment]
I am a bit confused. In ipywidgets, apparently only one widget has 'tooltip':

<img width="854" alt="screen shot 2017-10-01 at 9 18 27 pm" src="https://user-images.githubusercontent.com/1929/31058589-1fa9b6f2-a6ee-11e7-9d27-2c206e7c5764.png">

The rest do not. The rest have 'description', which is both the label and the tooltip...is that right?

<img width="858" alt="screen shot 2017-10-01 at 9 21 49 pm" src="https://user-images.githubusercontent.com/1929/31058618-90934982-a6ee-11e7-8db0-f9c3d68319a1.png">

<img width="387" alt="screen shot 2017-10-01 at 9 20 17 pm" src="https://user-images.githubusercontent.com/1929/31058611-706f1ef6-a6ee-11e7-96a7-76664cc5c3cb.png">

So we have to do this kind of thing:

<img width="756" alt="screen shot 2017-10-01 at 9 23 19 pm" src="https://user-images.githubusercontent.com/1929/31058641-cb8fdb72-a6ee-11e7-96d4-19aa12a6b744.png">

**Comment by jbednar** [comment]
> The rest have 'description', which is both the label and the tooltip...is that right?

I think I wrote that bit, and there's no way I would have resorted to CSS if it was working properly without it.  I don't remember the details, though!  Seems very strange that only one widget supports tooltips, but maybe so...

**Comment by jbednar** [comment]
And in any case, using the same text for the label and tooltip does not seem reasonable at all!

**Comment by ceball** [comment]
I don't know why ipywidgets does that, although in my own experience tooltips are not something people expect on websites so maybe nobody's really paid any attention. I wonder if we should in general be doing something other than tooltips/hover? E.g. on a phone/tablet, hover is awkward - you usually need something people see they should touch.

**Comment by ceball** [comment]
Anyway, maybe we could fix the tooltips by using what I think is the accepted (?) way to do tooltips in html5, i.e. adding a `title` attribute. Maybe? E.g. https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title

**Comment by ceball** [comment]
Using `title` for the tooltip:

<img width="501" alt="screen shot 2017-10-02 at 11 59 59 am" src="https://user-images.githubusercontent.com/1929/31074651-8f80c4a4-a769-11e7-9ef5-2b13a154cd38.png">

At least for me in my browser, the tooltip takes longer to appear than it did before.

**Comment by ceball** [comment]
Fixed by #72
