### ISSUE TITLE
Widget could not be displayed because the widget state could not be found

### ISSUE THREAD

**Issue by bacalfa** [ioam/paramnb#80]
After saving the notebook, closing it, shutting down the kernel, and reopening everything, I get the following message.

`A Jupyter widget could not be displayed because the widget state could not be found. This could happen if the kernel storing the widget is no longer available, or if the widget state was not saved in the notebook. You may be able to create the widget by running the appropriate cells.`

The plot remains intact, but the widgets disappear. So I have to rerun the notebook to regenerate the widgets. Is this normal?

**Comment by jbednar** [comment]
In my experience, having innumerable unexplained issues with ipywidgets is normal. :-(  That's the main reason we switched to focusing on parambokeh; we were simply never able to get a reliable ipywidgets configuration.  Parambokeh is still very rough around the edges, but we have just started a big project to improve it, so you should be seeing rapid advances in parambokeh and only minor bugfixes in paramb for now.  So, I recommend that you try to get things working well for you in parambokeh, and file issues there.
